---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
spec:
  minReadySeconds: 4
  replicas: 4
  selector:
    matchLabels:
      app: jenkins
      version: "v1.0"
  strategy: 
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%    
  template:
    metadata:
      labels:
        app: jenkins
        version: "v1.0"
    spec:
      containers:
        - name: jenkins
          image: jenkins:1.651.3-alpine
          ports:
            - containerPort: 8080
              protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-svc
spec:
  type: NodePort
  selector:
    app: jenkins
  ports:
    - name: webport
      targetPort: 8080
      port: 35000
      nodePort: 32000    
   

        

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat
spec:
  minReadySeconds: 3
  replicas: 2
  selector:
    matchLabels:
      app: tomcat
      version: "1.0"
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      name: tomcat
      labels:
        app: tomcat
        version: "1.0"
    spec:
      containers:
        - name: tomcat
          image: tomcat:10
          ports:
            - containerPort: 8080
              protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: tomcat-svc
spec:
  type: LoadBalancer
  selector:
    app: tomcat
  ports:
    - targetPort: 8080
      port: 80
      #nodePort: 32000
      protocol: TCP
