apiVersion: v1
kind: ReplicationController
metadata:
  name: gameoflife
spec:
  minReadySeconds: 2
  replicas: 5
  selector: 
    app: gameoflife
    version: "1.0"
  template: 
    metadata:
      name: gameoflife
      labels:
        app: gameoflife
        version: "1.0"
    spec: 
      initContainers:
        - name: alpine
          image: alpine:1.0
          command:
            - sleep
          args:
            - "2m"  
      containers:
        - name: openmrs
          image: maheshryali/gameoflife:1.0
          ports:
            - containerPort: 8080
              protocol: TCP




---
apiVersion: v1
kind: ReplicationController
metadata: 
  name: nodejs
spec:
  minReadySeconds: 4
  replicas: 5
  selector: 
    app: nodejs
    version: "v1.0"
  template:
    metadata:
      name: nodejsapp
      labels:
        app: nodejs
        version: "v1.0"
    spec:
      containers:
        - name: nodejs
          image: maheshryali/nodejs:1.0    
            




---
apiVersion: v1
kind: ReplicationController
metadata:
  name: openmrsapp
spec:
  minReadySeconds: 3
  replicas: 5
  selector:
    version: "1.0"
  template:
    metadata:
      name: openmrs
      labels:
        app: openmrsapp
        version: "1.0"
    spec:
      containers:
        - name: openmrscont
          image: maheshryali/openmrs:1.0
          ports:
            - containerPort: 8080
              protocol: TCP
